FROM node:20-alpine
# working directory
WORKDIR /app

#  copy only package files (best practice)
ADD backend/package*.json ./

# install dependencies
RUN npm install
# copy complete backend code
ADD backend .
# expose backend port (jo tum use kar rahe ho)
EXPOSE 8000


CMD ["node","app.js" ]