FROM node:20-alpine


# Set working directory inside container
WORKDIR /app

# Copy package.json and package-lock.json first
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

ENV BACKEND_URL=http://0.0.0.0:8000

# Copy rest of frontend code
ADD frontend /app

# Command to run dev server
CMD ["npm", "run", "dev"]

